name: Check links in Markdown files
on:
  schedule:
    - cron: 0 0 * * 1   # midnight every Monday
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          file-path: ./README.md, ./CONTRIBUTING.md
          folder-path: docs
